fileExtensions:
  - php
mappings:
  SilverStripe\Filesystem\Storage\AssetContainer: SilverStripe\Assets\Storage\AssetContainer
  AssetNameGenerator: SilverStripe\Assets\Storage\AssetNameGenerator
  SilverStripe\Filesystem\Storage\AssetNameGenerator: SilverStripe\Assets\Storage\AssetNameGenerator
  AssetStore: SilverStripe\Assets\Storage\AssetStore
  SilverStripe\Filesystem\Storage\AssetStore: SilverStripe\Assets\Storage\AssetStore
  SilverStripe\Filesystem\Storage\AssetStoreRouter: SilverStripe\Assets\Storage\AssetStoreRouter
  SilverStripe\Filesystem\Storage\DBFile: SilverStripe\Assets\Storage\DBFile
  SilverStripe\Filesystem\Storage\DefaultAssetNameGenerator: SilverStripe\Assets\Storage\DefaultAssetNameGenerator
  GeneratedAssetHandler: SilverStripe\Assets\Storage\GeneratedAssetHandler
  SilverStripe\Filesystem\Storage\GeneratedAssetHandler: SilverStripe\Assets\Storage\GeneratedAssetHandler
  SilverStripe\Filesystem\Storage\ProtectedFileController: SilverStripe\Assets\Storage\ProtectedFileController
  ProtectedFileController: SilverStripe\Assets\Storage\ProtectedFileController
  SilverStripe\Filesystem\Flysystem\AssetAdapter: SilverStripe\Assets\Flysystem\AssetAdapter
  SilverStripe\Filesystem\Flysystem\FlysystemAssetStore: SilverStripe\Assets\Flysystem\FlysystemAssetStore
  SilverStripe\Filesystem\Storage\FlysystemGeneratedAssetHandler: SilverStripe\Assets\Flysystem\GeneratedAssets
  SilverStripe\Assets\Flysystem\GeneratedAssetHandler: SilverStripe\Assets\Flysystem\GeneratedAssets
  SilverStripe\Filesystem\Flysystem\ProtectedAdapter: SilverStripe\Assets\Flysystem\ProtectedAdapter
  SilverStripe\Filesystem\Flysystem\ProtectedAssetAdapter: SilverStripe\Assets\Flysystem\ProtectedAssetAdapter
  SilverStripe\Filesystem\Flysystem\PublicAdapter: SilverStripe\Assets\Flysystem\PublicAdapter
  SilverStripe\Filesystem\Flysystem\PublicAssetAdapter: SilverStripe\Assets\Flysystem\PublicAssetAdapter
  SilverStripe\Filesystem\AssetControlExtension: SilverStripe\Assets\AssetControlExtension
  SilverStripe\Filesystem\AssetManipulationList: SilverStripe\Assets\AssetManipulationList
  SilverStripe\Filesystem\Thumbnail: SilverStripe\Assets\Thumbnail
  SilverStripe\Filesystem\ImageManipulation: SilverStripe\Assets\ImageManipulation
  DBFileTest: SilverStripe\Assets\Tests\Storage\DBFileTest
  DBFileTest_Object: SilverStripe\Assets\Tests\Storage\DBFileTest\TestObject
  DBFileTest_Subclass: SilverStripe\Assets\Tests\Storage\DBFileTest\Subclass
  DBFileTest_ImageOnly: SilverStripe\Assets\Tests\Storage\DBFileTest\ImageOnly
  File: SilverStripe\Assets\File
  SS_FileFinder: SilverStripe\Assets\FileFinder
  SilverStripe\Assets\SS_FileFinder: SilverStripe\Assets\FileFinder
  FileMigrationHelper: SilverStripe\Assets\FileMigrationHelper
  FileNameFilter: SilverStripe\Assets\FileNameFilter
  Filesystem: SilverStripe\Assets\Filesystem
  Folder: SilverStripe\Assets\Folder
  Image: SilverStripe\Assets\Image
  Image_Backend: SilverStripe\Assets\Image_Backend
  Upload: SilverStripe\Assets\Upload
  Upload_Validator: SilverStripe\Assets\Upload_Validator
  AssetControlExtensionTest: SilverStripe\Assets\Tests\AssetControlExtensionTest
  AssetControlExtensionTest_VersionedObject: SilverStripe\Assets\Tests\AssetControlExtensionTest\VersionedObject
  AssetControlExtensionTest_Object: SilverStripe\Assets\Tests\AssetControlExtensionTest\TestObject
  AssetControlExtensionTest_ArchivedObject: SilverStripe\Assets\Tests\AssetControlExtensionTest\ArchivedObject
  AssetManipulationListTest: SilverStripe\Assets\Tests\AssetManipulationListTest
  FileFinderTest: SilverStripe\Assets\Tests\FileFinderTest
  FileMigrationHelperTest: SilverStripe\Assets\Tests\FileMigrationHelperTest
  FileMigrationHelperTest_Extension: SilverStripe\Assets\Tests\FileMigrationHelperTest\Extension
  FileNameFilterTest: SilverStripe\Assets\Tests\FileNameFilterTest
  FileTest: SilverStripe\Assets\Tests\FileTest
  FileTest_MyCustomFile: SilverStripe\Assets\Tests\FileTest\MyCustomFile
  FolderTest: SilverStripe\Assets\Tests\FolderTest
  GDTest: SilverStripe\Assets\Tests\GDImageTest
  ProtectedFileControllerTest: SilverStripe\Assets\Tests\ProtectedFileControllerTest
  UploadTest: SilverStripe\Assets\Tests\UploadTest
  UploadTest_Validator: SilverStripe\Assets\Tests\UploadTest\Validator
  GDImageTest: SilverStripe\Assets\Tests\GDImageTest
  ImageTest: SilverStripe\Assets\Tests\ImageTest
  ImagickImageTest: SilverStripe\Assets\Tests\ImagickImageTest
  AssetStoreTest_SpyStore: SilverStripe\Assets\Dev\TestAssetStore
  SilverStripe\Assets\Tests\Storage\AssetStoreTest\TestAssetStore: SilverStripe\Assets\Dev\TestAssetStore
  AssetAdapterTest: SilverStripe\Assets\Tests\Flysystem\AssetAdapterTest
  FlysystemPublicAdapter: SilverStripe\Assets\Flysystem\PublicAdapter
  FlysystemProtectedAdapter: SilverStripe\Assets\Flysystem\ProtectedAdapter
  # Service definitions - Not classes
  FlysystemPublicBackend: League\Flysystem\Filesystem.public
  FlysystemProtectedBackend: League\Flysystem\Filesystem.protected
skipConfigs:
  - db
  - casting
  - table_name
  - fixed_fields
  - menu_title
  - allowed_actions
  - plural_name
  - singular_name
  - owns
  - searchable_fields
  - summary_fields
  - default_search_filter_class
  - segment
skipYML:
  - Filesystem
warnings:
  methods:
    'SilverStripe\Assets\File->setFilename()':
      message: 'Filenames should not be set directly anymore'
      url: 'https://docs.silverstripe.org/en/4/changelogs/4.0.0#write-file-dataobject'
    'SilverStripe\Assets\File::handle_shortcode()':
      message: 'Has been removed'
      url: 'https://docs.silverstripe.org/en/4/changelogs/4.0.0#file-shortcode'
    'SilverStripe\Assets\Filesystem::sync()':
      message: 'Removed'
    'SilverStripe\Assets\Folder::syncChildren()':
      message: 'Removed'
    'SilverStripe\Assets\Folder::constructChild()':
      message: 'Removed'
    'SilverStripe\Assets\Folder::addUploadToFolder()':
      message: 'Removed'
    'SilverStripe\Assets\File::deletedatabaseOnly()':
      message: 'Removed'
    'SilverStripe\Assets\File::link_shortcode_handler()':
      message: 'Removed'
    'SilverStripe\Assets\File::getRelativePath()':
      message: 'Removed'
    'SilverStripe\Assets\File::getFullPath()':
      message: 'Removed'
    'SilverStripe\Assets\File::setParentID()':
      message: 'Removed'
    'SilverStripe\Assets\Image::regenerateFormattedImages()':
      message: 'Removed'
    'SilverStripe\Assets\Image::getGeneratedImages()':
      message: 'Removed'
    'SilverStripe\Assets\Image::deleteFormattedImages()':
      message: 'Removed'
    'SilverStripe\Assets\Image::handle_shortcode()':
      message: 'moved to SilverStripe\Assets\Shortcodes\ImageShortcodeProvider::handle_shortcode()'
    'SilverStripe\Assets\Image::SetRatioSize()':
      message: 'Renamed to Fit()'
      replacement: 'Fit'
    'SilverStripe\Assets\Image::SetWidth()':
      message: 'Renamed to ScaleWidth()'
      replacement: 'ScaleWidth'
    'SilverStripe\Assets\Image::SetHeight()':
      message: 'Renamed to ScaleHeight'
      replacement: 'ScaleHeight'
    'SilverStripe\Assets\Image::SetSize()':
      message: 'Renamed to Pad()'
      replacement: 'Pad'
    'SilverStripe\Assets\Image::PaddedImage()':
      message: 'Renamed to Pad()'
      replacement: 'Pad'
    'SilverStripe\Assets\Image::CroppedImage()':
      message: 'Renamed to Fill()'
      replacement: 'Fill'
    'SilverStripe\Assets\Image::AssetLibraryPreview()':
      message: 'Renamed to PreviewThumbnail()'
      replacement: 'PreviewThumbnail'
    'SilverStripe\Assets\Image::AssetLibraryThumbnail()':
      message: 'Renamed to CMSThumbnail()'
      replacement: 'CMSThumbnail'
